### **Classification using sklearn and keras (with pandas)**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<font color="red">File access required:</font> In Colab this notebook requires first uploading files **Cities.csv**, **Players.csv**, and **Titanic.csv** using the *Files* feature in the left toolbar. If running the notebook on a local computer, simply ensure these files are in the same workspace as the notebook.

In [4]:
# Set-up
import csv
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from keras import Sequential
from keras.layers import Dense
from numpy.random import seed
import tensorflow

### Prepare Cities data for classification
Predict <i>temperature category</i> from other features

In [5]:
# Read Cities.csv into dataframe, add column for temperature category
# Note: For a dataframe D and integer i, D.loc[i] is the i-th row of D
f = open('/content/drive/MyDrive/Google Colab/Machine Learning Using Python/Copy of Cities.csv')
cities = pd.read_csv(f)
categories = []
for i in range(len(cities)):
    if cities.loc[i]['temperature'] < 5:
        categories.append('cold')
    elif cities.loc[i]['temperature'] < 9:
        categories.append('cool')
    elif cities.loc[i]['temperature'] < 15:
        categories.append('warm')
    else: categories.append('hot')
cities['category'] = categories
print("cold:", len(cities[(cities.category == 'cold')]))
print("cool:", len(cities[(cities.category == 'cool')]))
print("warm:", len(cities[(cities.category == 'warm')]))
print("hot:", len(cities[(cities.category == 'hot')]))

cold: 17
cool: 92
warm: 79
hot: 25

In [30]:
# Create training and test sets for cities data
numitems = len(cities)
percenttrain = 0.85
numtrain = int(numitems*percenttrain)
print('Training set', numtrain, 'items')
print('Test set', numitems - numtrain, 'items')
citiesTrain = cities[0:numtrain]
citiesTest = cities[numtrain:]

citiesTest

Training set 181 items
Test set 32 items

             city         country  latitude  longitude  temperature category
181         Sivas          Turkey     39.75      37.03         8.05     cool
182        Skopje       Macedonia     42.00      21.43         9.36     warm
183         Split         Croatia     43.52      16.47        12.46     warm
184  Stara Zagora        Bulgaria     42.42      25.62        10.90     warm
185     Stavanger          Norway     58.97       5.68         5.53     cool
186     Stockholm          Sweden     59.35      18.10         6.26     cool
187          Sumy         Ukraine     50.92      34.78         6.28     cool
188       Swansea  United Kingdom     51.63      -3.95         9.73     warm
189        Szeged         Hungary     46.25      20.15        10.34     warm
190       Tallinn         Estonia     59.43      24.73         4.82     cold
191       Tampere         Finland     61.50      23.75         3.59     cold
192        Tarsus          Turkey     36.92      34.88        11.21     warm
193         Tartu         Estonia     58.38      26.71         4.36     cold
194      Tekirdag          Turkey     40.99      27.51        13.02     warm
195      Toulouse          France     43.62       1.45        10.25     warm
196       Trabzon          Turkey     40.98      39.72        10.28     warm
197       Trieste           Italy     45.65      13.80        11.21     warm
198       Trikala          Greece     39.56      21.77        16.00      hot
199     Trondheim          Norway     63.42      10.42         4.53     cold
200         Turku         Finland     60.45      22.25         4.72     cold
201       Uppsala          Sweden     59.86      17.64         4.17     cold
202      Valencia           Spain     39.49      -0.40        16.02      hot
203        Vienna         Austria     48.20      16.37         7.86     cool
204          Vigo           Spain     42.22      -8.73        12.85     warm
205       Vilnius       Lithuania     54.68      25.32         5.38     cool
206        Warsaw          Poland     52.25      21.00         7.20     cool
207       Wroclaw          Poland     51.11      17.03         7.17     cool
208   Yevpatoriya         Ukraine     45.20      33.36        10.02     warm
209      Zaragoza           Spain     41.65      -0.89        14.17     warm
210      Zhytomyr         Ukraine     50.25      28.66         6.67     cool
211     Zonguldak          Turkey     41.43      31.78        10.64     warm
212        Zurich     Switzerland     47.38       8.56         6.68     cool

### K-nearest-neighbors classification

In [ ]:
features = ['longitude', 'latitude']
neighbors = 10
predict = 'category'

# steps of machine learning
classifier = KNeighborsClassifier(neighbors)
classifier.fit(citiesTrain[features], citiesTrain[predict])
predictions = classifier.predict(citiesTest[features])
# print(predictions)

# Calculate accuracy
actuals = list(citiesTest[predict])
correct = 0
for i in range(len(actuals)):
  print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))
# Comment out print, try different values for neighbors, different features

Predicted: warm  Actual: cool
Predicted: warm  Actual: warm
Predicted: warm  Actual: warm
Predicted: warm  Actual: warm
Predicted: cool  Actual: cool
Predicted: cool  Actual: cool
Predicted: cool  Actual: cool
Predicted: cool  Actual: warm
Predicted: warm  Actual: warm
Predicted: cool  Actual: cold
Predicted: cool  Actual: cold
Predicted: warm  Actual: warm
Predicted: cool  Actual: cold
Predicted: warm  Actual: warm
Predicted: warm  Actual: warm
Predicted: warm  Actual: warm
Predicted: warm  Actual: warm
Predicted: hot  Actual: hot
Predicted: cool  Actual: cold
Predicted: cool  Actual: cold
Predicted: cool  Actual: cold
Predicted: warm  Actual: hot
Predicted: cool  Actual: cool
Predicted: warm  Actual: warm
Predicted: cool  Actual: cool
Predicted: cool  Actual: cool
Predicted: cool  Actual: cool
Predicted: cool  Actual: warm
Predicted: warm  Actual: warm
Predicted: cool  Actual: cool
Predicted: warm  Actual: warm
Predicted: cool  Actual: cool
Accuracy: 0.6875

### <font color="green">**Your Turn: K-nearest-neighbors on World Cup data**</font>
<font color="green">Predict <i>position</i> from one or more of <i>minutes, shots, passes, tackles, saves</i></font>

In [22]:
# This cell does all the set-up, including reordering the data to avoid team bias.
f = open('/content/drive/MyDrive/Google Colab/Machine Learning Using Python/Copy of Players.csv')
players = pd.read_csv(f)
players = players.sort_values(by='surname')
players = players.reset_index(drop=True)
numitems = len(players)
percenttrain = 0.92
numtrain = int(numitems*percenttrain)
print('Training set', numtrain, 'items')
print('Test set', numitems - numtrain, 'items')
playersTrain = players[0:numtrain]
playersTest = players[numtrain:]

Training set 547 items
Test set 48 items

In [41]:
# This cell does the classification.
# Try different features and different numbers of neighbors.
# What's the highest accuracy you can get?
features = ['shots','tackles']
neighbors = 30
predict = 'position'
classifier = KNeighborsClassifier(neighbors)
classifier.fit(playersTrain[features], playersTrain[predict])
predictions = classifier.predict(playersTest[features])
# Calculate accuracy
actuals = list(playersTest[predict])
correct = 0
for i in range(len(actuals)):
  print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))
# Comment out print, try different values for neighbors, different features

Predicted: defender  Actual: midfielder
Predicted: goalkeeper  Actual: goalkeeper
Predicted: forward  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: midfielder  Actual: forward
Predicted: midfielder  Actual: midfielder
Predicted: midfielder  Actual: midfielder
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: defender  Actual: defender
Predicted: midfielder  Actual: forward
Predicted: defender  Actual: defender
Predicted: midfielder  Actual: defender
Predicted: midfielder  Actual: defender
Predicted: forward  Actual: forward
Predicted: goalkeeper  Actual: goalkeeper
Predicted: defender  Actual: defender
Predicted: forward  Actual: forward
Predicted: defender  Actual: defender
Predicted: midfielder  Actual: forward
Predicted: forward  Actual: forward
Predicted: midfielder  Actual: midfielder
Predicted: forward  Actual: forward
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: midfielder
Predicted: forward  Actual: forward
Predicted: midfielder  Actual: midfielder
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: forward  Actual: midfielder
Predicted: forward  Actual: forward
Predicted: goalkeeper  Actual: forward
Predicted: midfielder  Actual: midfielder
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: defender  Actual: defender
Predicted: defender  Actual: defender
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: forward  Actual: forward
Predicted: defender  Actual: midfielder
Predicted: defender  Actual: midfielder
Predicted: defender  Actual: midfielder
Predicted: midfielder  Actual: midfielder
Predicted: defender  Actual: defender
Predicted: forward  Actual: forward
Predicted: defender  Actual: defender
Accuracy: 0.70833

### <font color="green">**Your Turn Extra: K-nearest-neighbors on Titanic data**</font>
<font color="green">Predict <i>survived</i> from one or more of <i>gender, age, class, fare, embarked</i></font>

In [29]:
# This cell does all the set-up
f = open('/content/drive/MyDrive/Google Colab/Machine Learning Using Python/Copy of Titanic.csv')
titanic = pd.read_csv(f)
# Convert gender and embarked to numeric values and missing ages to average age
titanic['gender'].replace({'M':0, 'F':1}, inplace=True)
titanic['embarked'].replace({'Cherbourg':0, 'Southampton':1, 'Queenstown':2}, inplace=True)

avg_age = np.average(titanic['age'].dropna().tolist())
titanic['age'].fillna(avg_age, inplace=True)

# Create training and test sets
numitems = len(titanic)
percenttrain = 0.92
numtrain = int(numitems*percenttrain)
print('Training set', numtrain, 'items')
print('Test set', numitems - numtrain, 'items')
titanicTrain = titanic[0:numtrain]
titanicTest = titanic[numtrain:]

titanicTest.head(10)

Training set 819 items
Test set 72 items

<ipython-input-29-2851180100>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['gender'].replace({'M':0, 'F':1}, inplace=True)
<ipython-input-29-2851180100>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titanic['gender'].replace({'M':0, 'F':1}, inplace=True)
<ipython-input-29-2851180100>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embarked'].replace({'Cherbourg':0, 'Southampton':1, 'Queenstown':2}, inplace=True)
<ipython-input-29-2851180100>:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titanic['embarked'].replace({'Cherbourg':0, 'Southampton':1, 'Queenstown':2}, inplace=True)
<ipython-input-29-2851180100>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['age'].fillna(avg_age, inplace=True)

,last,first,gender,age,class,fare,embarked,survived
819,Toomey,Miss Ellen,1,50.000000,2,10.50,1,yes
820,Torber,Mr. Ernst William,0,44.000000,3,8.05,1,no
821,Tornquist,Mr. William Henry,0,25.000000,3,0.00,1,yes
822,Toufik,Mr. Nakli,0,29.699118,3,7.23,0,no
823,Touma,Mrs. Darwis (Hanne Youssef Razi),1,29.000000,3,15.25,0,yes
824,Troupiansky,Mr. Moses Aaron,0,23.000000,2,13.00,1,no
825,Trout,Mrs. William H (Jessie L),1,28.000000,2,12.65,1,yes
826,Troutt,"Miss Edwina Celia ""Winnie""",1,27.000000,2,10.50,1,yes
827,Turcin,Mr. Stjepan,0,36.000000,3,7.90,1,no
828,Turja,Miss Anna Sofia,1,18.000000,3,9.84,1,yes

In [ ]:
# This cell does the classification.
# Try different features and different numbers of neighbors.
# What's the highest accuracy you can get?
features = ['gender', 'age', 'class', 'fare', 'embarked']
neighbors = 10
predict = 'survived'
classifier = KNeighborsClassifier(neighbors)
classifier.fit(titanicTrain[features], titanicTrain[predict])
predictions = classifier.predict(titanicTest[features])
# Calculate accuracy
actuals = list(titanicTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.86111

### Decision tree classification

In [38]:
features = ['longitude','latitude']
split = 20
predict = 'category'
dt = DecisionTreeClassifier(random_state=0, min_samples_split=split) # split parameter is optional
dt.fit(citiesTrain[features], citiesTrain[predict])
predictions = dt.predict(citiesTest[features])
# Calculate accuracy
actuals = list(citiesTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))
# Try different values for split, different features

Accuracy: 0.78125

### "Forest" of decision trees

In [ ]:
features = ['longitude', 'latitude']
split = 3
trees = 15
predict = 'category'
rf = RandomForestClassifier(random_state=0, min_samples_split=split, n_estimators=trees)
rf.fit(citiesTrain[features], citiesTrain[predict])
predictions = rf.predict(citiesTest[features])
# Calculate accuracy
actuals = list(citiesTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))
# Try different values for split and trees, different features

Accuracy: 0.9375

### <font color="green">**Your Turn: Decision tree and forest of trees on World Cup data**</font>

In [40]:
# SINGLE TREE
# Try different features and different values for split.
# What's the highest accuracy you can get?
features = ['minutes', 'shots', 'tackles']
split = 30
predict = 'position'
dt = DecisionTreeClassifier(random_state=0, min_samples_split=split) # parameter is optional
dt.fit(playersTrain[features], playersTrain[predict])
predictions = dt.predict(playersTest[features])
# Calculate accuracy
actuals = list(playersTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.77083

In [33]:
# FOREST OF TREES
# Try different features and different values for split and trees.
# What's the highest accuracy you can get?
features = ['minutes', 'shots', 'passes']
split = 26
trees = 9
predict = 'position'
rf = RandomForestClassifier(random_state=0, min_samples_split=split, n_estimators=trees)
rf.fit(playersTrain[features], playersTrain[predict])
predictions = rf.predict(playersTest[features])
# Calculate accuracy
actuals = list(playersTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.79167

### <font color="green">**Your Turn Extra: Decision tree and forest of trees on Titanic data**</font>

In [ ]:
# SINGLE TREE
# Try different features and different values for split.
# What's the highest accuracy you can get?
features = ['gender', 'age', 'class', 'fare', 'embarked']
split = 10
predict = 'survived'
dt = DecisionTreeClassifier(random_state=0, min_samples_split=split) # parameter is optional
dt.fit(titanicTrain[features], titanicTrain[predict])
predictions = dt.predict(titanicTest[features])
# Calculate accuracy
actuals = list(titanicTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.80556

In [37]:
# FOREST OF TREES
# Try different features and different values for split and trees.
# What's the highest accuracy you can get?
features = ['gender', 'age', 'class', 'fare', 'embarked']
split = 46
trees = 7
predict = 'survived'
rf = RandomForestClassifier(random_state=0, min_samples_split=split, n_estimators=trees)
rf.fit(titanicTrain[features], titanicTrain[predict])
predictions = rf.predict(titanicTest[features])
# Calculate accuracy
actuals = list(titanicTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.80556

### Naive Bayes classification

In [31]:
features = ['latitude']
predict = 'category'
nb = GaussianNB()
nb.fit(citiesTrain[features], citiesTrain[predict])
predictions = nb.predict(citiesTest[features])
# Calculate accuracy
actuals = list(citiesTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))
# Try different features

Accuracy: 0.84375

### <font color="green">**Your Turn: Naive Bayes on World Cup data**</font>

In [20]:
# Try different features. What's the highest accuracy you can get?
features = ['shots', 'passes', 'tackles', 'saves']
predict = 'position'
nb = GaussianNB()
nb.fit(playersTrain[features], playersTrain[predict])
predictions = nb.predict(playersTest[features])
# Calculate accuracy
actuals = list(playersTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.75

### <font color="green">**Your Turn Extra: Naive Bayes on Titanic data**</font>

In [19]:
# Try different features. What's the highest accuracy you can get?
features = ['gender']
predict = 'survived'
nb = GaussianNB()
nb.fit(titanicTrain[features], titanicTrain[predict])
predictions = nb.predict(titanicTest[features])
# Calculate accuracy
actuals = list(titanicTest[predict])
correct = 0
for i in range(len(actuals)):
# print('Predicted:', predictions[i], ' Actual:', actuals[i])
  if predictions[i] == actuals[i]: correct +=1
print('Accuracy:', round(correct/len(actuals),5))

Accuracy: 0.81944

### Neural network classification

In [ ]:
features = ['longitude', 'latitude']
num_layers = 5 # including input and output, so must be >= 2
num_epochs = 20 # number of iterations over training data
batchsize = 20 # size of each batch during one iteration
layer_outputs = 32 # dimensionality of output of each layer
epoch_tracing = 'yes'
predict = 'category'
# Normalize feature values
sc = StandardScaler()
featurevals_train = sc.fit_transform(citiesTrain[features])
featurevals_test = sc.fit_transform(citiesTest[features])
# Encode labels
encoder = LabelEncoder()
encoder.fit(cities[predict])
labels_train = encoder.transform(citiesTrain[predict])
labels_test = encoder.transform(citiesTest[predict])
# Set up neural-net classifier
seed(1) # to eliminate some randomness
tensorflow.random.set_seed(1) # to eliminate more randomness
classifier = Sequential()
# Input layer
classifier.add(Dense(layer_outputs, activation='relu', input_dim=len(features)))
# Hidden layers
for i in range(num_layers-2):
    classifier.add(Dense(layer_outputs, activation='relu',))
# Output layer - first arg is number of labels, softmax for multi-class classification
classifier.add(Dense(4, activation='softmax'))
classifier.compile(optimizer ='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy'])
# Fit to training data
if epoch_tracing == 'yes': v = 2
else: v = 0
hist = classifier.fit(featurevals_train, labels_train, batch_size=batchsize, epochs=num_epochs, verbose=v)
print('Number of epochs:', num_epochs)
print('Final accuracy on training data:', hist.history['accuracy'][-1])
# Evaluate on test data
test_acc = classifier.evaluate(featurevals_test, labels_test, verbose=0)[1]
print('Accuracy on test data:', test_acc)
# Try different values for num_layers, num_epochs, batch size, layer_outputs, and different features

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/20
10/10 - 3s - 322ms/step - accuracy: 0.4530 - loss: 1.3330
Epoch 2/20
10/10 - 0s - 5ms/step - accuracy: 0.4972 - loss: 1.2421
Epoch 3/20
10/10 - 0s - 6ms/step - accuracy: 0.5470 - loss: 1.1629
Epoch 4/20
10/10 - 0s - 4ms/step - accuracy: 0.6243 - loss: 1.0915
Epoch 5/20
10/10 - 0s - 7ms/step - accuracy: 0.6519 - loss: 1.0308
Epoch 6/20
10/10 - 0s - 5ms/step - accuracy: 0.6685 - loss: 0.9776
Epoch 7/20
10/10 - 0s - 6ms/step - accuracy: 0.6630 - loss: 0.9301
Epoch 8/20
10/10 - 0s - 6ms/step - accuracy: 0.6630 - loss: 0.8834
Epoch 9/20
10/10 - 0s - 6ms/step - accuracy: 0.6685 - loss: 0.8402
Epoch 10/20
10/10 - 0s - 5ms/step - accuracy: 0.6740 - loss: 0.7994
Epoch 11/20
10/10 - 0s - 6ms/step - accuracy: 0.6851 - loss: 0.7599
Epoch 12/20
10/10 - 0s - 5ms/step - accuracy: 0.6851 - loss: 0.7225
Epoch 13/20
10/10 - 0s - 6ms/step - accuracy: 0.6906 - loss: 0.6875
Epoch 14/20
10/10 - 0s - 6ms/step - accuracy: 0.7182 - loss: 0.6549
Epoch 15/20
10/10 - 0s - 4ms/step - accuracy: 0.7514 - loss: 0.6251
Epoch 16/20
10/10 - 0s - 6ms/step - accuracy: 0.7514 - loss: 0.5986
Epoch 17/20
10/10 - 0s - 6ms/step - accuracy: 0.7735 - loss: 0.5757
Epoch 18/20
10/10 - 0s - 6ms/step - accuracy: 0.7901 - loss: 0.5576
Epoch 19/20
10/10 - 0s - 6ms/step - accuracy: 0.7901 - loss: 0.5426
Epoch 20/20
10/10 - 0s - 6ms/step - accuracy: 0.8011 - loss: 0.5291
Number of epochs: 20
Final accuracy on training data: 0.8011049628257751
Accuracy on test data: 0.65625

### <font color="green">**Your Turn: Neural network on World Cup data**</font>

In [16]:
# Try different features and different values for num_layers, num_epochs,
#  batch size, and layer_outputs.
# What's the highest accuracy you can get?
# Note: Although some randomness is removed by setting seeds in the code,
#  you may still see somewhat different accuracy on different runs;
#  changing the order of the features can also affect accuracy
features = ['minutes', 'shots', 'tackles', 'saves']
num_layers = 5 # including input and output, so must be >= 2
num_epochs = 30 # number of iterations over training data
batchsize = 10 # size of each batch during one iteration
layer_outputs = 64 # dimensionality of output of each layer
epoch_tracing = 'no'
predict = 'position'
# Normalize feature values
sc = StandardScaler()
featurevals_train = sc.fit_transform(playersTrain[features])
featurevals_test = sc.fit_transform(playersTest[features])
# Encode labels
encoder = LabelEncoder()
encoder.fit(players[predict])
labels_train = encoder.transform(playersTrain[predict])
labels_test = encoder.transform(playersTest[predict])
# Set up neural-net classifier
seed(1) # to eliminate some randomness
tensorflow.random.set_seed(1) # to eliminate more randomness
classifier = Sequential()
# Input layer
classifier.add(Dense(layer_outputs, activation='relu', input_dim=len(features)))
# Hidden layers
for i in range(num_layers-2):
    classifier.add(Dense(layer_outputs, activation='relu',))
# Output layer - first arg is number of labels, softmax for multi-class classification
classifier.add(Dense(4, activation='softmax'))
classifier.compile(optimizer ='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy'])
# Fit to training data
if epoch_tracing == 'yes': v = 2
else: v = 0
hist = classifier.fit(featurevals_train, labels_train, batch_size=batchsize, epochs=num_epochs, verbose=v)
print('Number of epochs:', num_epochs)
print('Final accuracy on training data:', hist.history['accuracy'][-1])
# Evaluate on test data
test_acc = classifier.evaluate(featurevals_test, labels_test, verbose=0)[1]
print('Accuracy on test data:', test_acc)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Number of epochs: 30
Final accuracy on training data: 0.6416819095611572
Accuracy on test data: 0.6875

### <font color="green">**Your Turn Extra: Neural network on Titanic data**</font>

In [15]:
# Try different features and different values for num_layers, num_epochs,
#  batch size, and layer_outputs.
# What's the highest accuracy you can get?
# Note: Although some randomness is removed by setting seeds in the code,
#  you may still see somewhat different accuracy on different runs;
#  changing the order of the features can also affect accuracy
features = ['gender', 'age', 'class', 'fare', 'embarked']
num_layers = 5 # including input and output, so must be >= 2
num_epochs = 30 # number of iterations over training data
batchsize = 10 # size of each batch during one iteration
layer_outputs = 64 # dimensionality of output of each layer
epoch_tracing = 'no'
predict = 'survived'
# Normalize feature values
sc = StandardScaler()
featurevals_train = sc.fit_transform(titanicTrain[features])
featurevals_test = sc.fit_transform(titanicTest[features])
# Encode labels
encoder = LabelEncoder()
encoder.fit(titanic[predict])
labels_train = encoder.transform(titanicTrain[predict])
labels_test = encoder.transform(titanicTest[predict])
# Set up neural-net classifier
seed(1) # to eliminate some randomness
tensorflow.random.set_seed(1) # to eliminate more randomness
classifier = Sequential()
# Input layer
classifier.add(Dense(layer_outputs, activation='relu', input_dim=len(features)))
# Hidden layers
for i in range(num_layers-2):
    classifier.add(Dense(layer_outputs, activation='relu',))
# Output layer - first arg is number of labels, softmax for multi-class classification
classifier.add(Dense(2, activation='softmax'))
classifier.compile(optimizer ='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy'])
# Fit to training data
if epoch_tracing == 'yes': v = 2
else: v = 0
hist = classifier.fit(featurevals_train, labels_train, batch_size=batchsize, epochs=num_epochs, verbose=v)
print('Number of epochs:', num_epochs)
print('Final accuracy on training data:', hist.history['accuracy'][-1])
# Evaluate on test data
test_acc = classifier.evaluate(featurevals_test, labels_test, verbose=0)[1]
print('Accuracy on test data:', test_acc)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Number of epochs: 30
Final accuracy on training data: 0.8400488495826721
Accuracy on test data: 0.8333333134651184